import { db, aiThreads, aiMessages, aiConfigs } from '@baubar/db'
import { eq, asc, and, desc } from 'drizzle-orm'
import type { Channel, ThreadMessage } from './types'

const HISTORY_LIMIT = 40 // rolling window — last N messages sent to LLM

/**
 * Find or create the default thread for (orgId, channel, externalId).
 * externalId is the user UUID for web/mobile, E.164 phone for WhatsApp.
 */
export async function getOrCreateThread(
  orgId: string,
  channel: Channel,
  externalId: string,
): Promise<string> {
  const existing = await db
    .select({ id: aiThreads.id })
    .from(aiThreads)
    .where(and(
      eq(aiThreads.org_id, orgId),
      eq(aiThreads.channel, channel),
      eq(aiThreads.external_id, externalId),
    ))
    .orderBy(desc(aiThreads.created_at))
    .limit(1)

  if (existing[0]) return existing[0].id

  const [created] = await db
    .insert(aiThreads)
    .values({ org_id: orgId, channel, external_id: externalId })
    .returning({ id: aiThreads.id })

  return created!.id
}

/**
 * Create a fresh thread — used when the user starts a new conversation.
 * Uses a unique external_id so multiple threads can exist per user.
 */
export async function createFreshThread(
  orgId: string,
  channel: Channel,
  userId: string,
): Promise<string> {
  const [created] = await db
    .insert(aiThreads)
    .values({ org_id: orgId, channel, external_id: `${userId}:${Date.now()}` })
    .returning({ id: aiThreads.id })
  return created!.id
}

/** Verify a thread belongs to the given org (ownership check). */
export async function verifyThreadOwnership(threadId: string, orgId: string): Promise<boolean> {
  const [row] = await db
    .select({ id: aiThreads.id })
    .from(aiThreads)
    .where(and(eq(aiThreads.id, threadId), eq(aiThreads.org_id, orgId)))
    .limit(1)
  return !!row
}

/** Load the full message history for a thread (all roles incl. tool results), oldest first.
 *  Used by the agent to reconstruct the full conversation context for the LLM. */
export async function loadHistory(threadId: string): Promise<ThreadMessage[]> {
  const rows = await db
    .select({ role: aiMessages.role, content: aiMessages.content })
    .from(aiMessages)
    .where(eq(aiMessages.thread_id, threadId))
    .orderBy(asc(aiMessages.seq))
    .limit(HISTORY_LIMIT)

  return rows.map((r) => ({
    role: r.role as ThreadMessage['role'],
    content: r.content as ThreadMessage['content'],
  }))
}

/** Load only user + final assistant text messages for display in the web/mobile chat UI.
 *  Filters out tool-call, tool-result, and intermediate assistant messages. */
export async function loadDisplayHistory(threadId: string): Promise<{ role: 'user' | 'assistant'; content: string }[]> {
  const rows = await db
    .select({ role: aiMessages.role, content: aiMessages.content })
    .from(aiMessages)
    .where(eq(aiMessages.thread_id, threadId))
    .orderBy(asc(aiMessages.seq))

  return rows.flatMap((r) => {
    if (r.role === 'user') {
      const text = typeof r.content === 'string' ? r.content : (r.content as any)?.[0]?.text ?? ''
      return [{ role: 'user' as const, content: text }]
    }
    if (r.role === 'assistant') {
      // Only include assistant messages that contain at least one text part
      const content = r.content
      if (typeof content === 'string') return [{ role: 'assistant' as const, content }]
      if (Array.isArray(content)) {
        const text = (content as any[]).find((p) => p.type === 'text')?.text
        if (text) return [{ role: 'assistant' as const, content: text }]
      }
    }
    return []
  })
}

/** Load the org's custom system prompt from ai.configs, or null if not set. */
export async function loadOrgConfig(orgId: string): Promise<string | null> {
  const [row] = await db
    .select({ system_prompt: aiConfigs.system_prompt })
    .from(aiConfigs)
    .where(eq(aiConfigs.org_id, orgId))
    .limit(1)
  return row?.system_prompt ?? null
}

/**
 * Persist a full conversation turn in the thread.
 *
 * @param userContent   - The user's message content
 * @param responseMessages - All messages generated by the model during this turn
 *   (CoreAssistantMessage + CoreToolMessage[]), as returned by
 *   `generateText().response.messages`. These are stored as-is in JSONB so the
 *   LLM can see tool call results (e.g. created report IDs) in future turns —
 *   without them ever appearing in the user-facing chat response.
 */
export async function persistTurn(
  threadId: string,
  userContent: ThreadMessage['content'],
  responseMessages: { role: string; content: unknown }[],
): Promise<void> {
  await db.insert(aiMessages).values([
    { thread_id: threadId, role: 'user', content: userContent },
    ...responseMessages.map((m) => ({ thread_id: threadId, role: m.role, content: m.content })),
  ])
}
